### PR TITLE
Add chronic filter and column to VBNL

### PR DESCRIPTION
**Pull request by gwenbeebe**
Here we go! 

I added it just as a text column...I looked at applying colors to another column, but that is not sortable, or using icons, but at four different levels that starts to be confusing. I thought about using icons for just chronic/aged in/nearly and leaving not chronic blank, but I'm worried that might make users think the information is missing.

Anyway, that's my thought process behind making it it's own text column! But of course let me know if you'd rather go with one of the other options and I'll switch it over.

### CODE REVIEW

**Comment by kiadso** [comment]
I think text is probably the best idea here too. Factoring it can give us custom sorting options and it works really well in the datatable framework, so that could be helpful here! Let me know if you want to try that before I merge this or if you want me to add it later. :)
I think this will add a lot to the report- thank you so much for getting this piece together!

**Comment by gwenbeebe** [comment]
Of course! I did set it up as a factor where I created it in `COHHIO_HMIS`, that sorting seems to be working in the app. It's in "Chronic", "Aged In", "Nearly Chronic", "Not Chronic" order right now, let me know if you want those changed?

**Comment by kiadso** [comment]
Ohh, right, sorry I hadn't checked COHHIO_HMIS, no this is perfect, thank you!

**Comment by kiadso** [comment]
I love this! I just published it to R minor elevated as is. :)

**Pull request merged**
